version: '3.7'
services:
  mysql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=pass